name: sample-golang-kafka-2
envs:
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_BROKER
    value: ${mykafka.HOSTNAME}:${mykafka.PORT}
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_TOPIC
    value: sample-topic
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_USERNAME
    value: ${mykafka.USERNAME}
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_PASSWORD
    value: ${mykafka.PASSWORD}
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_CA_CERT
    value: ${mykafka.CA_CERT}
databases:
  - cluster_name: mykafka
    db_user: doadmin
    engine: KAFKA
    name: mykafka
    production: true
services:
  - name: producer
    source_dir: producer
    github:
      repo: digitalocean/sample-golang-kafka
      branch: main
workers:
  - name: consumer
    source_dir: consumer
    github:
      repo: digitalocean/sample-golang-kafka
      branch: main
